### ISSUE TITLE
History Readings löschen geht nicht

### ISSUE THREAD

**Issue by Medel** [Askie666/VE.Direct#1]
Clear_History geht nicht in Fhem. Wie lösche ich die immer größere Zahl an History Readings ohne sie einzeln zu löschern

**Comment by Askie666** [comment]
Der Befehl Clear_History löscht die Historie im angeschlossenen Gerät und nicht in die in FHEM angelegten Readings. 
Die können nur per "deletereading <name> History_.*" gelöscht werden
